### PR TITLE
Solves the issue for undefined gates (cr2, cr4, cr8, crz)

### PR DESCRIPTION
**Pull request by Kaustuvi**
Hi @perak,
This PR solves the issues mentioned in #21. Please let me know if there are mistakes/other workarounds! :)

### CODE REVIEW

**Comment by perak** [comment]
Hi @Kaustuvi 

Thank you very much for the PR, but problem is that almost entire file is changed and it is hard for review:

Screen Shot 2019-06-10 at 6 53 42 AM

Looks like you (or your editor) changed coding style and there is more than 2k changes.

Can you pls change only code where you find bugs and make new PR?

**Comment by perak** [comment]
Plus, my latest commit is shown in diff, so looks like something is messed up with git.

I will merge your changes, but please try to make new clean branch and modify code there.

Thanks!

**Comment by Kaustuvi** [comment]
I probably formatted the file and that's why there are so many changes. Also, I merged your latest commit after raising the PR and that probably messed up something! I am sorry for this mistake. :(
Should I make a new PR now?

**Comment by perak** [comment]
It is best if you make new one. Thanks!

**Comment by Kaustuvi** [comment]
Okay! I am making a new one! :)

**Pull request closed without merging**
